source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

gem 'foreigner'

gem 'auto_strip_attributes', '~> 1.0'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem "font-awesome-rails", "~> 3.0.2.0"
 gem 'bootstrap-wysihtml5-rails'


gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

gem 'bootstrap-sass'

gem 'debugger'


gem 'devise','2.0.4'

gem 'paperclip'

gem 'simple_form'

gem "googlecharts", :require => "gchart"

gem 'omniauth-facebook','1.3.0'

gem 'omniauth'

gem 'will_paginate', '~> 3.0'

gem 'dynamic_form'

gem 'client_side_validations'
